// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, Client, TDataShape } from "./client";
import type {
  GetUserInfoData,
  GetUserInfoResponses,
  GetUserInfoErrors,
  RefreshTokenData,
  RefreshTokenResponses,
  RefreshTokenErrors,
  LogoutData,
  LogoutResponses,
  LogoutErrors,
  VerifyTokenData,
  VerifyTokenResponses,
  VerifyTokenErrors,
  LoginPageInfoData,
  LoginPageInfoResponses,
  ReadItemData,
  ReadItemResponses,
  ReadItemErrors,
  CreateItemData,
  CreateItemResponses,
  CreateItemErrors,
  DeleteItemData,
  DeleteItemResponses,
  DeleteItemErrors,
  HealthCheckData,
  HealthCheckResponses,
  LivenessData,
  LivenessResponses,
  ReadinessData,
  ReadinessResponses,
} from "./types.gen";
import { client } from "./client.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get User Info
 * Get current user information.
 *
 * Returns the authenticated user's details from the JWT token.
 */
export const getUserInfo = <ThrowOnError extends boolean = false>(
  options?: Options<GetUserInfoData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetUserInfoResponses,
    GetUserInfoErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/auth/me",
    ...options,
  });
};

/**
 * Refresh Token
 * Refresh access token.
 *
 * Note: In a production Keycloak setup, token refresh is typically
 * handled by the frontend using the refresh_token grant directly
 * with Keycloak. This endpoint serves as a proxy for convenience.
 *
 * For now, this returns a placeholder response. The actual refresh
 * flow should be implemented by the frontend calling Keycloak directly.
 */
export const refreshToken = <ThrowOnError extends boolean = false>(
  options?: Options<RefreshTokenData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    RefreshTokenResponses,
    RefreshTokenErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/auth/refresh",
    ...options,
  });
};

/**
 * Logout
 * Logout endpoint.
 *
 * Note: In a Keycloak setup, logout is typically handled by
 * redirecting the user to Keycloak's logout endpoint.
 * This endpoint serves as a notification hook.
 *
 * Frontend should redirect to:
 * {KEYCLOAK_URL}/realms/{realm}/protocol/openid-connect/logout?
 * redirect_uri={frontend_url}
 */
export const logout = <ThrowOnError extends boolean = false>(
  options?: Options<LogoutData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    LogoutResponses,
    LogoutErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/auth/logout",
    ...options,
  });
};

/**
 * Verify Token
 * Verify that the current token is valid.
 *
 * Returns user information if token is valid.
 */
export const verifyToken = <ThrowOnError extends boolean = false>(
  options?: Options<VerifyTokenData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    VerifyTokenResponses,
    VerifyTokenErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/auth/verify",
    ...options,
  });
};

/**
 * Login Page Info
 * Get login page information for frontend.
 *
 * Returns the Keycloak login URL and configuration for the frontend
 * to initiate the OAuth flow.
 */
export const loginPageInfo = <ThrowOnError extends boolean = false>(
  options?: Options<LoginPageInfoData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    LoginPageInfoResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/auth/login",
    ...options,
  });
};

/**
 * Read Item
 */
export const readItem = <ThrowOnError extends boolean = false>(
  options?: Options<ReadItemData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ReadItemResponses,
    ReadItemErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/items/",
    ...options,
  });
};

/**
 * Create Item
 */
export const createItem = <ThrowOnError extends boolean = false>(
  options: Options<CreateItemData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateItemResponses,
    CreateItemErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/items/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete Item
 */
export const deleteItem = <ThrowOnError extends boolean = false>(
  options: Options<DeleteItemData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteItemResponses,
    DeleteItemErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/items/{item_id}",
    ...options,
  });
};

/**
 * Health Check
 * Health check endpoint for infrastructure services.
 *
 * Returns status of PostgreSQL, Redis, and Keycloak connectivity.
 * Returns 200 if all services are healthy, 503 otherwise.
 */
export const healthCheck = <ThrowOnError extends boolean = false>(
  options?: Options<HealthCheckData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    HealthCheckResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/health",
    ...options,
  });
};

/**
 * Liveness
 * Simple liveness probe for container orchestration.
 */
export const liveness = <ThrowOnError extends boolean = false>(
  options?: Options<LivenessData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    LivenessResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/health/live",
    ...options,
  });
};

/**
 * Readiness
 * Readiness probe - only returns 200 if dependencies are ready.
 */
export const readiness = <ThrowOnError extends boolean = false>(
  options?: Options<ReadinessData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ReadinessResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/health/ready",
    ...options,
  });
};
