// This file is auto-generated by @hey-api/openapi-ts

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * ItemCreate
 */
export type ItemCreate = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Quantity
   */
  quantity?: number | null;
};

/**
 * ItemRead
 */
export type ItemRead = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Quantity
   */
  quantity?: number | null;
  /**
   * Id
   */
  id: string;
  /**
   * User Id
   */
  user_id: string;
};

/**
 * Page[ItemRead]
 */
export type PageItemRead = {
  /**
   * Items
   */
  items: Array<ItemRead>;
  /**
   * Total
   */
  total?: number | null;
  /**
   * Page
   */
  page: number | null;
  /**
   * Size
   */
  size: number | null;
  /**
   * Pages
   */
  pages?: number | null;
};

/**
 * TokenResponse
 * Response model for token endpoints.
 */
export type TokenResponse = {
  /**
   * Access Token
   */
  access_token: string;
  /**
   * Refresh Token
   */
  refresh_token?: string | null;
  /**
   * Token Type
   */
  token_type?: string;
  /**
   * Expires In
   */
  expires_in: number;
};

/**
 * UserInfoResponse
 * Response model for user info.
 */
export type UserInfoResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Email
   */
  email: string;
  /**
   * Is Active
   */
  is_active: boolean;
  /**
   * Is Verified
   */
  is_verified: boolean;
  /**
   * Is Superuser
   */
  is_superuser: boolean;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

export type GetUserInfoData = {
  body?: never;
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null;
  };
  path?: never;
  query?: never;
  url: "/auth/me";
};

export type GetUserInfoErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetUserInfoError = GetUserInfoErrors[keyof GetUserInfoErrors];

export type GetUserInfoResponses = {
  /**
   * Successful Response
   */
  200: UserInfoResponse;
};

export type GetUserInfoResponse =
  GetUserInfoResponses[keyof GetUserInfoResponses];

export type RefreshTokenData = {
  body?: never;
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null;
  };
  path?: never;
  query?: never;
  url: "/auth/refresh";
};

export type RefreshTokenErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RefreshTokenError = RefreshTokenErrors[keyof RefreshTokenErrors];

export type RefreshTokenResponses = {
  /**
   * Successful Response
   */
  200: TokenResponse;
};

export type RefreshTokenResponse =
  RefreshTokenResponses[keyof RefreshTokenResponses];

export type LogoutData = {
  body?: never;
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null;
  };
  path?: never;
  query?: never;
  url: "/auth/logout";
};

export type LogoutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
  /**
   * Response Auth-Logout
   * Successful Response
   */
  200: {
    [key: string]: string;
  };
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type VerifyTokenData = {
  body?: never;
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null;
  };
  path?: never;
  query?: never;
  url: "/auth/verify";
};

export type VerifyTokenErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type VerifyTokenError = VerifyTokenErrors[keyof VerifyTokenErrors];

export type VerifyTokenResponses = {
  /**
   * Successful Response
   */
  200: UserInfoResponse;
};

export type VerifyTokenResponse =
  VerifyTokenResponses[keyof VerifyTokenResponses];

export type LoginPageInfoData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/auth/login";
};

export type LoginPageInfoResponses = {
  /**
   * Response Auth-Login Page Info
   * Successful Response
   */
  200: {
    [key: string]: string;
  };
};

export type LoginPageInfoResponse =
  LoginPageInfoResponses[keyof LoginPageInfoResponses];

export type ReadItemData = {
  body?: never;
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null;
  };
  path?: never;
  query?: {
    /**
     * Page
     * Page number
     */
    page?: number;
    /**
     * Size
     * Page size
     */
    size?: number;
  };
  url: "/items/";
};

export type ReadItemErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadItemError = ReadItemErrors[keyof ReadItemErrors];

export type ReadItemResponses = {
  /**
   * Successful Response
   */
  200: PageItemRead;
};

export type ReadItemResponse = ReadItemResponses[keyof ReadItemResponses];

export type CreateItemData = {
  body: ItemCreate;
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null;
  };
  path?: never;
  query?: never;
  url: "/items/";
};

export type CreateItemErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateItemError = CreateItemErrors[keyof CreateItemErrors];

export type CreateItemResponses = {
  /**
   * Successful Response
   */
  200: ItemRead;
};

export type CreateItemResponse = CreateItemResponses[keyof CreateItemResponses];

export type DeleteItemData = {
  body?: never;
  headers?: {
    /**
     * Authorization
     */
    authorization?: string | null;
  };
  path: {
    /**
     * Item Id
     */
    item_id: string;
  };
  query?: never;
  url: "/items/{item_id}";
};

export type DeleteItemErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteItemError = DeleteItemErrors[keyof DeleteItemErrors];

export type DeleteItemResponses = {
  /**
   * Response Item-Delete Item
   * Successful Response
   */
  200: {
    [key: string]: string;
  };
};

export type DeleteItemResponse = DeleteItemResponses[keyof DeleteItemResponses];

export type HealthCheckData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health";
};

export type HealthCheckResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type LivenessData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health/live";
};

export type LivenessResponses = {
  /**
   * Response Health-Liveness
   * Successful Response
   */
  200: {
    [key: string]: string;
  };
};

export type LivenessResponse = LivenessResponses[keyof LivenessResponses];

export type ReadinessData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health/ready";
};

export type ReadinessResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ClientOptions = {
  baseURL: "http://localhost:8000" | (string & {});
};
